# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'permissions': [('view_future_post', 'Can view unpublished Post')], 'verbose_name': 'blog post'},
        ),
    ]
